services:
  postgresserver:
    # image: postgres:17.5 navicat连接报错
    image: postgres:14.18
    container_name: postgres
    restart: always
    shm_size: 128mb
    environment:
      LANG: 'C.UTF-8'
      POSTGRES_PASSWORD: 'post123'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    ports:
      - '8080:5432'
    volumes:
      - '/etc/localtime:/etc/localtime'
      - '/etc/timezone:/etc/timezone'
      - './data:/var/lib/postgresql/data'
